name: Build and Deploy Front and Back

on:
  workflow_dispatch:
  push:
    tags:
      - 'v**' # Déclenche l'exécution uniquement pour les tags qui commencent par "v" et on 3 nombre avec un point entre chaque

env:
  ARTIFACTS_PATH: ${{ github.workspace }}/artifacts
  SOURCES_DIR: sources

jobs:
  deploy-front:
    name: Deploy Front
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy package on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/installations/commandCraftor/front
            npm run updateDeploy

  deploy-back:
    name: Deploy Back
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy package on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/installations/commandCraftor/back
            npm run updateDeploy
