name: Build and Deploy Front and Back

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Déclenche l'exécution uniquement pour les tags qui commencent par "v"

jobs:
  execute-script:
    name: Execute Script on VPS
    runs-on: ubuntu-latest

    steps:
      # 1. Exécuter le script sur le VPS
      - name: Run script on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            bash ~/scripts/deployCommandCraftorAll.sh
