name: Update Submodule Front

on:
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le dépôt principal
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2. Configurer SSH pour les submodules
      - name: Setup SSH for Submodules
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_SUBMODULES }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

      # 3. Mettre à jour le submodule spécifique
      - name: Update submodule
        run: |
          cd front
          git reset --hard origin/main
          cd ..

      # 4. Commit et push des changements
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add front
          git commit -m 'Update submodule /front' || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
